language: objective-c
osx_image: xcode7.2
before_install:
- brew update
- brew install carthage || brew outdated carthage || brew upgrade carthage
install:
- gem install xcpretty
- carthage bootstrap
script:
- set -o pipefail && xcodebuild -scheme 'rcmdClientTests' -sdk iphonesimulator test | xcpretty -c

