language: objective-c
osx_image: xcode7.2
before_install:
- brew update
- brew install carthage || brew outdated carthage || brew upgrade carthage
install:
- gem install xcpretty
- carthage bootstrap
script:
- set -o pipefail && xcodebuild -scheme 'rcmdClientTests' -destination 'platform=iOS Simulator,name=iPhone 6s'  test| xcpretty -c 
- env:
    global:
        secure: 5b3fcbdc03ffb4c50a709d082cab4ef4d1a02a69
